## server config
#spring:
# datasource:
#   username: root
#   password: root
#   url: jdbc:mysql://localhost:3306/sc_copy?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#messages:
#  basename: i18n.login
##国际化
#server:
#  port: 8080
## thymleaf
##不规则html5
#thymeleaf:
#   mode: LEGACYHTML5
#   cache: false
## mybatis
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
## log4j2
#logging:
#  config: classpath:log4j2.yml
#
#
#
#
#
#
#
